### ISSUE TITLE
Annotation changes are not visible until a rebuild of the project

### ISSUE THREAD

**Issue by gayanper** [microsoft/build-server-for-gradle#192]
When using annotation processors like RecordBuilder https://github.com/Randgalt/record-builder, the generated the builder classes are not visible to JDT until a full rebuild is done on the project.

**Comment by jdneo** [comment]
Yes, I guess the reason is that currently the JDT.LS side will not delegate the build to gradle when AUTO_BUILD event comes.

**Comment by Tanish-Ranjan** [comment]
If you saying that Gradle Build Server requires a rebuild in order to get JDT to recognize all the generated classes then, that is the intended Gradle behavior I think. Many annotation processors work that way as I have seen in Android as well.

Otherwise if you are saying that Gradle Build Server is not rebuilding automatically as the annotations are applied then: A [workspace reload](https://build-server-protocol.github.io/docs/specification#workspacereload-request) request must be sent to the Gradle Build Server for rebuilding the project. @jdneo is there a way for users to reload the workspace in JDT?

Was I able to understand your issue clearly? @gayanper

**Comment by gayanper** [comment]
I can confirm this works as expected with latest version. I assume it was an issue with my workspace and extensions. hence closing this issue.
